apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flink.fullname" . }}-config
  labels:
{{ include "flink.labels" . | indent 4 }}
data:
  flink-conf.yaml: |+
{{- if .Values.jobmanager.highAvailability.enabled }}
        jobmanager.rpc.address: REPLACE_HOSTNAME
{{- end }}
{{ include "flink.configuration" . | indent 4 }}
  flink-conf-taskmanager.yaml: |+
{{ include "flink.configuration" . | indent 4 }}
  log4j.properties: |+
{{ .Values.flink.logging.log4j_properties | indent 4 }}
  log4j-cli.properties: |+
{{ .Values.flink.logging.log4j_cli_properties | indent 4 }}
  log4j-session.properties: |+
{{ .Values.flink.logging.log4j_session_properties | indent 4 }}
  security.properties:
    # The java-level namelookup cache policy for successful lookups
    networkaddress.cache.ttl=30
