{{- if and .Values.sharedWebUploadDir.enabled (eq .Values.sharedWebUploadDir.useExistingPVC false) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flink-web-upload-dir
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sharedWebUploadDir.size | quote }}
  storageClassName: {{ .Values.sharedWebUploadDir.storageClass | quote }}
{{- end }}
